added Samurai theme
morpheusthewhite/spicetify-themes pull request #295
Opened 2021-03-20 22:43 UTC by no3l0815

added a new theme

2021-03-20 22:53 UTC, no3l0815 commented
It's my first pull request so please text me if i did something wrong.

2021-03-21 08:31 UTC, morpheusthewhite commented
There is no README, please add it to the folder as explained here https://github.com/morpheusthewhite/spicetify-themes#contributions

2021-03-21 10:54 UTC, no3l0815 commented
I added now the README

2021-03-21 17:10 UTC, morpheusthewhite requested changes

2021-03-21 17:10 UTC, morpheusthewhite commented on Samurai/README.md
> +#more
Correct the headers and check the preview https://github.com/no3l0815/spicetify-themes/tree/master/Samurai

2021-03-21 17:18 UTC, no3l0815 reviewed
everythings ok

2021-03-22 06:42 UTC, morpheusthewhite commented
Nope, spaces are needed between the #s and text or they will not be shown correctly (same for ##)

2021-03-23 18:55 UTC, morpheusthewhite requested changes
Please correct the README

2021-03-23 19:42 UTC, no3l0815 commented
i changed it now

2021-03-24 07:47 UTC, merged