Add Psycho Theme to V2
morpheusthewhite/spicetify-themes pull request #370
Opened 2021-05-20 07:44 UTC by harbassan

2021-05-20 21:29 UTC, harbassan commented
Well it is similar, but the UI has been slightly changed such as the player, which has the playback bar spanning the full width of the window, similar to the legacy SpicetifyDefault theme, along with the subheadings, and a few changes to the variables used to colour certain objects. That's about it really.

2021-05-21 05:49 UTC, morpheusthewhite commented
I think you could push it as color scheme to the existing `Default` theme since it is very similar.

Also I think I would be better to increase the contrast between the red and black to improve readability.

2021-05-21 06:14 UTC, harbassan commented
I mean considering that of the original legacy themes, a large amount have the playback bar as normal in the player, and a large amount have it as I do above the player, wouldn't it make sense to separate these into two different themes based on that? In the migration process you have.

2021-05-21 07:03 UTC, morpheusthewhite commented
If you ignore the size of the player then the only visible difference is the play button if I'm correct, so I think it's not necessary to create a different theme for that

2021-05-21 07:18 UTC, harbassan commented
I don't think you can tell from the screenshot I provided, maybe you can but I'm not sure.
![Screenshot](https://user-images.githubusercontent.com/84175605/119097332-b4588f80-ba68-11eb-8d98-f1c27619479a.png)
![Screenshot 2021-05-21 191454](https://user-images.githubusercontent.com/84175605/119097490-e5d15b00-ba68-11eb-8c59-a97ddb931378.png)
Many themes use either of these two, so it would be sensible to make two different themes because of this, right? That's what I saw in the themes you categorized in the migration process right? Sorry if you understand this already I'm just making sure.

2021-05-21 17:04 UTC, morpheusthewhite commented
You're, I overlooked the screenshot you uploaded, thanks for letting me know. Just update the colours and fix the conflicts and I'll merge it. 

I would also appreciate a more neutral theme name since we may want to push the color schemes I listed in the PR you mentioned, but I can't come up with a better one.

2021-05-22 02:28 UTC, harbassan commented
I've made the changes to the theme now. That was the best name I could think of.

2021-05-23 08:33 UTC, morpheusthewhite requested changes

2021-05-23 08:33 UTC, morpheusthewhite commented on THEMES.md
> +![Onepunch Screenshot](Onepunch/\__Home.png)
Put the themes in alphabetical order

2021-05-23 10:27 UTC, harbassan commented
done

2021-05-23 17:26 UTC, morpheusthewhite approved these changes

2021-05-23 17:26 UTC, merged