Added Burnt Sienna theme for xpui
morpheusthewhite/spicetify-themes pull request #406
Opened 2021-06-15 15:05 UTC by pjaspinski

2021-06-21 15:07 UTC, morpheusthewhite requested changes
Add the screenshot also to THEMES.md

2021-06-26 06:33 UTC, morpheusthewhite approved these changes

2021-06-26 06:34 UTC, morpheusthewhite commented on THEMES.md
> +![Burnt Sienna Screenshot](BurntSienna/screenshot.png)
The name of the theme is a single word.

2021-06-26 06:35 UTC, morpheusthewhite commented on THEMES.md
> +## Burnt Sienna
Theme should be ordered alphabetically

2021-06-26 06:36 UTC, morpheusthewhite requested changes
Correct THEMES.md

2021-06-26 08:52 UTC, pjaspinski commented
I made both requested changes - theme name is now one word and the screenshot is placed in THEMES.md in alphabetical order.

2021-06-29 17:55 UTC, morpheusthewhite approved these changes

2021-06-29 17:55 UTC, merged