Add dreary theme
morpheusthewhite/spicetify-themes pull request #469
Opened 2021-07-17 14:38 UTC by CharlieS1103

2021-07-18 06:01 UTC, morpheusthewhite commented
Why this PR?

2021-07-18 11:07 UTC, CharlieS1103 commented
@morpheusthewhite I worked on it a lot and I think its polished enough to be added to the repository.

2021-07-18 18:50 UTC, morpheusthewhite requested changes
I agree, the theme is much better than the initial one. Please do these small corrections and then I'll merge it

2021-07-18 18:50 UTC, morpheusthewhite commented on Dreary/README.md
> +##Important
Correct header. It is not correctly visualized

2021-07-18 18:50 UTC, morpheusthewhite commented on Dreary/README.md
> +Sidebar Config option must be enabled for theme to work properly, you can use it without, however some features may not be available, such as edits to the sidebar.
I may have missed this (since I think I already asked it to you) but what do you mean by this? Please clarify it in the README.

2021-07-18 18:55 UTC, morpheusthewhite commented
I also noticed some additional corrections about some elements not being visible:
- BIB and Deeper, time in song not visible
![image](https://user-images.githubusercontent.com/36999173/126078986-229128b5-d4fc-483e-b355-b9af9e2101dc.png)
![image](https://user-images.githubusercontent.com/36999173/126079031-9d208660-94b1-4ceb-b227-3f368fd94a29.png)
- Psycho, time in song not visible 
![image](https://user-images.githubusercontent.com/36999173/126079004-8d4e1771-9b08-44c1-a056-1b425739cc9f.png)

2021-07-18 22:30 UTC, CharlieS1103 commented
@morpheusthewhite I actually did correct that, just forget to change images.

2021-07-19 07:10 UTC, morpheusthewhite requested changes

2021-07-19 07:10 UTC, morpheusthewhite commented on Dreary/README.md
> +Certain aspects of the theme, such as the borders around playlist names, requires Sidebar Config to be enabled. It is not requires but recommended.
"required" instead of "requires". Explain how to enable this Sidebar Config.

2021-07-19 20:02 UTC, morpheusthewhite approved these changes

2021-07-19 20:04 UTC, merged