Add Glaze theme
morpheusthewhite/spicetify-themes pull request #654
Opened 2021-12-30 12:34 UTC by CharlieS1103

2021-12-31 07:39 UTC, morpheusthewhite commented
Can you summarize the main changes from the default theme?

2021-12-31 12:36 UTC, CharlieS1103 commented
@morpheusthewhite Uh there's quite a bit but sure, for starters the side bar was more or less changed rather massively, with there being some separation between elements, the selected tab having a different shape and a gradient, as well as the removal of some clutter. There's also the changes to the playbar and playbar controls which make it look rather organized and again, reduce clutter. The episodes, liked song, and create playlist buttons had the labels removed and reformatted to be less distracting. Probably a bit more to come but that's what I can think of off the top of my head

2022-01-02 11:29 UTC, morpheusthewhite requested changes

2022-01-02 11:29 UTC, morpheusthewhite commented on THEMES.md
> +<img src="https://github.com/CharlieS1103/Glaze-theme/blob/main/screenshots/base.png" alt="img" width="500px">
Do not use fixed-size images. Same in the README

2022-01-02 19:26 UTC, CharlieS1103 commented
@morpheusthewhite Done

2022-01-03 07:58 UTC, morpheusthewhite requested changes

2022-01-03 07:58 UTC, morpheusthewhite commented on Glaze/README.md
> +<img src="https://github.com/CharlieS1103/Glaze-theme/blob/main/screenshots/dark.png" alt="img" ">
There is a syntax error here, the image is not displayed. I wonder why you didn't just use the Markdown directive for displaying the images

2022-01-03 13:41 UTC, morpheusthewhite approved these changes

2022-01-03 13:41 UTC, merged