Update fluent.js
morpheusthewhite/spicetify-themes pull request #655
Opened 2022-01-04 05:37 UTC by Be1zebub

solved Uncaught TypeError: Cannot read properties of undefiend (reading 'Translations') at fluent.js:77
![](https://cdn.discordapp.com/attachments/924926223229014016/927544294678605874/unknown.png)

2022-01-04 05:52 UTC, Be1zebub commented
also sidebar icons fixed
before:
![before](https://user-images.githubusercontent.com/34854689/147931762-075ea598-04eb-4d23-baa0-82d10811786b.png)
after:
![after](https://i.imgur.com/BLaAKR4.png)

issue: #648

2022-01-04 06:33 UTC, Be1zebub commented
Now it looks almost divine.
![](https://i.imgur.com/cR9RKxa.png)
If we solve the problem with the nav buttons in header, it will be perfect.

2022-01-04 17:27 UTC, williamckha requested changes
Thanks for implementing the fixes. Sorry I haven't been maintaining this theme.
Unfortunately this solution of manually replacing the class names is temporary and the same issues will likely reoccur once Spotify updates. I was hoping that an updated css map in a new release of spicetify would resolve the issues, but spicetify hasn't released an update in a while.

2022-01-04 17:27 UTC, williamckha commented on Fluent/color.ini
> +[comfy]
Add a preview of this colour scheme in [THEMES.md](/morpheusthewhite/spicetify-themes/blob/master/THEMES.md)

2022-01-04 17:58 UTC, CharlieS1103 commented
@williamckha I attempted to fix the css map two weeks ago, however the changes didn't appear to change anything.

2022-01-05 07:10 UTC, williamckha commented
> @williamckha I attempted to fix the css map two weeks ago, however the changes didn't appear to change anything.

Thanks for letting me know. It's most likely that class names have been simply changed/removed over time from the mappings

2022-01-05 12:05 UTC, CharlieS1103 commented
@williamckha If you look at https://github.com/khanhas/spicetify-cli/commit/0689d4eac70887b75528158c2078b03eb019630e, you'll see that I attempted to map them to the same icon class to fix this, however the change didn't seem to affect anything for whatever reason

2022-01-05 18:42 UTC, Be1zebub commented
top bar back&forward buttons is also fixed, i used `:nth-child` to make it work for any spotify ver.
the only thing I can't fix is the play button above the playlist's thumb.
![](https://i.imgur.com/VPv7qUe.png)

2022-01-09 16:03 UTC, williamckha approved these changes

2022-01-09 16:10 UTC, merged